FIND_PATH(BALL_LIBRARY lib/libBALL.a  ${CMAKE_PREFIX_PATH} )
FIND_PATH(BALL_INCLUDE include/BALL/kernel.h ${CMAKE_PREFIX_PATH} )

IF(BALL_INCLUDE AND BALL_LIBRARY)
  SET(BALL_FOUND 1 CACHE BOOL "Found BALL library")
  SET(BALL_INCLUDE_DIR ${BALL_LIBRARY}/include)
  SET(BALL_LIBRARY_DIRS ${BALL_LIBRARY}/lib)
ELSE(BALL_INCLUDE AND BALL_LIBRARY)
  SET(BALL_FOUND 0 CACHE BOOL "Not found BALL library")
ENDIF(BALL_INCLUDE AND BALL_LIBRARY)

MARK_AS_ADVANCED(
  BALL_INCLUDE_DIR 
  BALL_LIBRARY 
  BALL_LIBRARY_DIRS 
  BALL_FOUND
)
