/********************************************************************************
** Form generated from reading ui file 'displayProperties.ui'
**
** Created: Wed Mar 19 14:28:17 2008
**      by: Qt User Interface Compiler version 4.2.2
**
** WARNING! All changes made in this file will be lost when recompiling ui file!
********************************************************************************/

#ifndef DISPLAYPROPERTIESDATA_H
#define DISPLAYPROPERTIESDATA_H

#include <BALL/COMMON/global.h>
#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QComboBox>
#include <QtGui/QDialog>
#include <QtGui/QGroupBox>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QRadioButton>
#include <QtGui/QSlider>

class Ui_DisplayPropertiesData
{
public:
    QPushButton *modify_button;
    QPushButton *create_button;
    QPushButton *close_button;
    QGroupBox *coloring_group;
    QLabel *textLabel1;
    QLabel *textLabel1_2_2_2;
    QComboBox *coloring_method_combobox;
    QLabel *transparency_label;
    QCheckBox *coloring_updates_enabled;
    QGroupBox *selection_group;
    QPushButton *edit_selection;
    QLabel *selection_color_label;
    QGroupBox *custom_group;
    QPushButton *custom_button;
    QLabel *custom_color_label;
    QSlider *transparency_slider;
    QGroupBox *model_group;
    QLabel *textLabel1_2;
    QComboBox *model_type_combobox;
    QLabel *textLabel1_2_2;
    QCheckBox *model_updates_enabled;
    QComboBox *mode_combobox;
    QGroupBox *resolution_group;
    QLabel *presets_precision_label;
    QLabel *custom_precision_label;
    QRadioButton *presets_precision_button;
    QRadioButton *custom_precision_button;
    QComboBox *precision_combobox;
    QSlider *precision_slider;
    QPushButton *model_options;
    QPushButton *coloring_options;

    void setupUi(QDialog *DisplayPropertiesData)
    {
    DisplayPropertiesData->setObjectName(QString::fromUtf8("DisplayPropertiesData"));
    QSizePolicy sizePolicy(static_cast<QSizePolicy::Policy>(0), static_cast<QSizePolicy::Policy>(0));
    sizePolicy.setHorizontalStretch(0);
    sizePolicy.setVerticalStretch(0);
    sizePolicy.setHeightForWidth(DisplayPropertiesData->sizePolicy().hasHeightForWidth());
    DisplayPropertiesData->setSizePolicy(sizePolicy);
    DisplayPropertiesData->setMinimumSize(QSize(570, 310));
    DisplayPropertiesData->setMaximumSize(QSize(570, 310));
    modify_button = new QPushButton(DisplayPropertiesData);
    modify_button->setObjectName(QString::fromUtf8("modify_button"));
    modify_button->setEnabled(false);
    modify_button->setGeometry(QRect(192, 277, 186, 30));
    QSizePolicy sizePolicy1(static_cast<QSizePolicy::Policy>(0), static_cast<QSizePolicy::Policy>(0));
    sizePolicy1.setHorizontalStretch(0);
    sizePolicy1.setVerticalStretch(0);
    sizePolicy1.setHeightForWidth(modify_button->sizePolicy().hasHeightForWidth());
    modify_button->setSizePolicy(sizePolicy1);
    modify_button->setMinimumSize(QSize(150, 30));
    modify_button->setMaximumSize(QSize(393, 28));
    modify_button->setFocusPolicy(Qt::TabFocus);
    modify_button->setAutoDefault(true);
    modify_button->setDefault(false);
    create_button = new QPushButton(DisplayPropertiesData);
    create_button->setObjectName(QString::fromUtf8("create_button"));
    create_button->setEnabled(false);
    create_button->setGeometry(QRect(1, 277, 186, 30));
    QSizePolicy sizePolicy2(static_cast<QSizePolicy::Policy>(0), static_cast<QSizePolicy::Policy>(0));
    sizePolicy2.setHorizontalStretch(0);
    sizePolicy2.setVerticalStretch(0);
    sizePolicy2.setHeightForWidth(create_button->sizePolicy().hasHeightForWidth());
    create_button->setSizePolicy(sizePolicy2);
    create_button->setMinimumSize(QSize(150, 30));
    create_button->setMaximumSize(QSize(393, 28));
    create_button->setFocusPolicy(Qt::TabFocus);
    create_button->setAutoDefault(true);
    create_button->setDefault(true);
    close_button = new QPushButton(DisplayPropertiesData);
    close_button->setObjectName(QString::fromUtf8("close_button"));
    close_button->setGeometry(QRect(383, 277, 186, 30));
    close_button->setMinimumSize(QSize(150, 30));
    close_button->setMaximumSize(QSize(393, 30));
    close_button->setFocusPolicy(Qt::TabFocus);
    close_button->setAutoDefault(true);
    coloring_group = new QGroupBox(DisplayPropertiesData);
    coloring_group->setObjectName(QString::fromUtf8("coloring_group"));
    coloring_group->setGeometry(QRect(286, 0, 283, 238));
    textLabel1 = new QLabel(coloring_group);
    textLabel1->setObjectName(QString::fromUtf8("textLabel1"));
    textLabel1->setGeometry(QRect(10, 17, 263, 16));
    textLabel1->setAlignment(Qt::AlignCenter);
    textLabel1_2_2_2 = new QLabel(coloring_group);
    textLabel1_2_2_2->setObjectName(QString::fromUtf8("textLabel1_2_2_2"));
    textLabel1_2_2_2->setGeometry(QRect(9, 154, 260, 16));
    textLabel1_2_2_2->setAlignment(Qt::AlignCenter);
    coloring_method_combobox = new QComboBox(coloring_group);
    coloring_method_combobox->setObjectName(QString::fromUtf8("coloring_method_combobox"));
    coloring_method_combobox->setGeometry(QRect(8, 33, 267, 24));
    coloring_method_combobox->setMinimumSize(QSize(160, 24));
    coloring_method_combobox->setMaximumSize(QSize(1600, 24));
    coloring_method_combobox->setFocusPolicy(Qt::StrongFocus);
    coloring_method_combobox->setMaxCount(2147483647);
    coloring_method_combobox->setInsertPolicy(QComboBox::InsertAtBottom);
    coloring_method_combobox->setDuplicatesEnabled(true);
    transparency_label = new QLabel(coloring_group);
    transparency_label->setObjectName(QString::fromUtf8("transparency_label"));
    transparency_label->setGeometry(QRect(222, 175, 50, 21));
    transparency_label->setAlignment(Qt::AlignCenter);
    coloring_updates_enabled = new QCheckBox(coloring_group);
    coloring_updates_enabled->setObjectName(QString::fromUtf8("coloring_updates_enabled"));
    coloring_updates_enabled->setGeometry(QRect(13, 203, 259, 27));
    selection_group = new QGroupBox(coloring_group);
    selection_group->setObjectName(QString::fromUtf8("selection_group"));
    selection_group->setGeometry(QRect(9, 67, 131, 80));
    selection_group->setFocusPolicy(Qt::NoFocus);
    selection_group->setAlignment(Qt::AlignHCenter);
    edit_selection = new QPushButton(selection_group);
    edit_selection->setObjectName(QString::fromUtf8("edit_selection"));
    edit_selection->setGeometry(QRect(52, 30, 70, 30));
    edit_selection->setMinimumSize(QSize(70, 30));
    edit_selection->setMaximumSize(QSize(70, 30));
    edit_selection->setFocusPolicy(Qt::TabFocus);
    edit_selection->setAutoDefault(true);
    selection_color_label = new QLabel(selection_group);
    selection_color_label->setObjectName(QString::fromUtf8("selection_color_label"));
    selection_color_label->setGeometry(QRect(6, 20, 40, 50));
    QPalette palette;
    QBrush brush(QColor(0, 0, 0, 255));
    brush.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
    QBrush brush1(QColor(221, 223, 228, 255));
    brush1.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Active, QPalette::Button, brush1);
    QBrush brush2(QColor(255, 255, 255, 255));
    brush2.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Active, QPalette::Light, brush2);
    QBrush brush3(QColor(255, 255, 255, 255));
    brush3.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
    QBrush brush4(QColor(85, 85, 85, 255));
    brush4.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
    QBrush brush5(QColor(199, 199, 199, 255));
    brush5.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
    QBrush brush6(QColor(0, 0, 0, 255));
    brush6.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Active, QPalette::Text, brush6);
    QBrush brush7(QColor(255, 255, 255, 255));
    brush7.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Active, QPalette::BrightText, brush7);
    QBrush brush8(QColor(0, 0, 0, 255));
    brush8.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Active, QPalette::ButtonText, brush8);
    QBrush brush9(QColor(255, 255, 255, 255));
    brush9.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Active, QPalette::Base, brush9);
    QBrush brush10(QColor(239, 239, 239, 255));
    brush10.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Active, QPalette::Window, brush10);
    QBrush brush11(QColor(0, 0, 0, 255));
    brush11.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Active, QPalette::Shadow, brush11);
    QBrush brush12(QColor(103, 141, 178, 255));
    brush12.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Active, QPalette::Highlight, brush12);
    QBrush brush13(QColor(255, 255, 255, 255));
    brush13.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Active, QPalette::HighlightedText, brush13);
    QBrush brush14(QColor(0, 0, 238, 255));
    brush14.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Active, QPalette::Link, brush14);
    QBrush brush15(QColor(82, 24, 139, 255));
    brush15.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Active, QPalette::LinkVisited, brush15);
    QBrush brush16(QColor(232, 232, 232, 255));
    brush16.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush16);
    QBrush brush17(QColor(0, 0, 0, 255));
    brush17.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush17);
    QBrush brush18(QColor(221, 223, 228, 255));
    brush18.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Inactive, QPalette::Button, brush18);
    QBrush brush19(QColor(255, 255, 255, 255));
    brush19.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Inactive, QPalette::Light, brush19);
    QBrush brush20(QColor(255, 255, 255, 255));
    brush20.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush20);
    QBrush brush21(QColor(85, 85, 85, 255));
    brush21.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Inactive, QPalette::Dark, brush21);
    QBrush brush22(QColor(199, 199, 199, 255));
    brush22.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Inactive, QPalette::Mid, brush22);
    QBrush brush23(QColor(0, 0, 0, 255));
    brush23.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Inactive, QPalette::Text, brush23);
    QBrush brush24(QColor(255, 255, 255, 255));
    brush24.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush24);
    QBrush brush25(QColor(0, 0, 0, 255));
    brush25.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush25);
    QBrush brush26(QColor(255, 255, 255, 255));
    brush26.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Inactive, QPalette::Base, brush26);
    QBrush brush27(QColor(239, 239, 239, 255));
    brush27.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Inactive, QPalette::Window, brush27);
    QBrush brush28(QColor(0, 0, 0, 255));
    brush28.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush28);
    QBrush brush29(QColor(103, 141, 178, 255));
    brush29.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Inactive, QPalette::Highlight, brush29);
    QBrush brush30(QColor(255, 255, 255, 255));
    brush30.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush30);
    QBrush brush31(QColor(0, 0, 238, 255));
    brush31.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Inactive, QPalette::Link, brush31);
    QBrush brush32(QColor(82, 24, 139, 255));
    brush32.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush32);
    QBrush brush33(QColor(232, 232, 232, 255));
    brush33.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush33);
    QBrush brush34(QColor(128, 128, 128, 255));
    brush34.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush34);
    QBrush brush35(QColor(221, 223, 228, 255));
    brush35.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Disabled, QPalette::Button, brush35);
    QBrush brush36(QColor(255, 255, 255, 255));
    brush36.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Disabled, QPalette::Light, brush36);
    QBrush brush37(QColor(255, 255, 255, 255));
    brush37.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush37);
    QBrush brush38(QColor(85, 85, 85, 255));
    brush38.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Disabled, QPalette::Dark, brush38);
    QBrush brush39(QColor(199, 199, 199, 255));
    brush39.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Disabled, QPalette::Mid, brush39);
    QBrush brush40(QColor(199, 199, 199, 255));
    brush40.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Disabled, QPalette::Text, brush40);
    QBrush brush41(QColor(255, 255, 255, 255));
    brush41.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush41);
    QBrush brush42(QColor(128, 128, 128, 255));
    brush42.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush42);
    QBrush brush43(QColor(239, 239, 239, 255));
    brush43.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Disabled, QPalette::Base, brush43);
    QBrush brush44(QColor(239, 239, 239, 255));
    brush44.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Disabled, QPalette::Window, brush44);
    QBrush brush45(QColor(0, 0, 0, 255));
    brush45.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush45);
    QBrush brush46(QColor(86, 117, 148, 255));
    brush46.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Disabled, QPalette::Highlight, brush46);
    QBrush brush47(QColor(255, 255, 255, 255));
    brush47.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush47);
    QBrush brush48(QColor(0, 0, 238, 255));
    brush48.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Disabled, QPalette::Link, brush48);
    QBrush brush49(QColor(82, 24, 139, 255));
    brush49.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush49);
    QBrush brush50(QColor(232, 232, 232, 255));
    brush50.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush50);
    selection_color_label->setPalette(palette);
    selection_color_label->setFocusPolicy(Qt::NoFocus);
    selection_color_label->setFrameShape(QFrame::WinPanel);
    selection_color_label->setFrameShadow(QFrame::Raised);
    selection_color_label->setLineWidth(0);
    selection_color_label->setMidLineWidth(0);
    selection_color_label->setTextFormat(Qt::AutoText);
    selection_color_label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
    selection_color_label->setMargin(0);
    custom_group = new QGroupBox(coloring_group);
    custom_group->setObjectName(QString::fromUtf8("custom_group"));
    custom_group->setGeometry(QRect(145, 67, 130, 80));
    custom_group->setFocusPolicy(Qt::NoFocus);
    custom_group->setAlignment(Qt::AlignHCenter);
    custom_button = new QPushButton(custom_group);
    custom_button->setObjectName(QString::fromUtf8("custom_button"));
    custom_button->setGeometry(QRect(52, 30, 70, 30));
    custom_button->setMinimumSize(QSize(70, 30));
    custom_button->setMaximumSize(QSize(70, 30));
    custom_button->setFocusPolicy(Qt::TabFocus);
    custom_button->setAutoDefault(true);
    custom_color_label = new QLabel(custom_group);
    custom_color_label->setObjectName(QString::fromUtf8("custom_color_label"));
    custom_color_label->setGeometry(QRect(6, 19, 40, 50));
    QPalette palette1;
    QBrush brush51(QColor(0, 0, 0, 255));
    brush51.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Active, QPalette::WindowText, brush51);
    QBrush brush52(QColor(221, 223, 228, 255));
    brush52.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Active, QPalette::Button, brush52);
    QBrush brush53(QColor(255, 255, 255, 255));
    brush53.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Active, QPalette::Light, brush53);
    QBrush brush54(QColor(255, 255, 255, 255));
    brush54.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Active, QPalette::Midlight, brush54);
    QBrush brush55(QColor(85, 85, 85, 255));
    brush55.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Active, QPalette::Dark, brush55);
    QBrush brush56(QColor(199, 199, 199, 255));
    brush56.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Active, QPalette::Mid, brush56);
    QBrush brush57(QColor(0, 0, 0, 255));
    brush57.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Active, QPalette::Text, brush57);
    QBrush brush58(QColor(255, 255, 255, 255));
    brush58.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Active, QPalette::BrightText, brush58);
    QBrush brush59(QColor(0, 0, 0, 255));
    brush59.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush59);
    QBrush brush60(QColor(255, 255, 255, 255));
    brush60.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Active, QPalette::Base, brush60);
    QBrush brush61(QColor(239, 239, 239, 255));
    brush61.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Active, QPalette::Window, brush61);
    QBrush brush62(QColor(0, 0, 0, 255));
    brush62.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Active, QPalette::Shadow, brush62);
    QBrush brush63(QColor(103, 141, 178, 255));
    brush63.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Active, QPalette::Highlight, brush63);
    QBrush brush64(QColor(255, 255, 255, 255));
    brush64.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Active, QPalette::HighlightedText, brush64);
    QBrush brush65(QColor(0, 0, 238, 255));
    brush65.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Active, QPalette::Link, brush65);
    QBrush brush66(QColor(82, 24, 139, 255));
    brush66.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Active, QPalette::LinkVisited, brush66);
    QBrush brush67(QColor(232, 232, 232, 255));
    brush67.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush67);
    QBrush brush68(QColor(0, 0, 0, 255));
    brush68.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush68);
    QBrush brush69(QColor(221, 223, 228, 255));
    brush69.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Inactive, QPalette::Button, brush69);
    QBrush brush70(QColor(255, 255, 255, 255));
    brush70.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Inactive, QPalette::Light, brush70);
    QBrush brush71(QColor(255, 255, 255, 255));
    brush71.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush71);
    QBrush brush72(QColor(85, 85, 85, 255));
    brush72.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush72);
    QBrush brush73(QColor(199, 199, 199, 255));
    brush73.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush73);
    QBrush brush74(QColor(0, 0, 0, 255));
    brush74.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Inactive, QPalette::Text, brush74);
    QBrush brush75(QColor(255, 255, 255, 255));
    brush75.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush75);
    QBrush brush76(QColor(0, 0, 0, 255));
    brush76.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush76);
    QBrush brush77(QColor(255, 255, 255, 255));
    brush77.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Inactive, QPalette::Base, brush77);
    QBrush brush78(QColor(239, 239, 239, 255));
    brush78.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Inactive, QPalette::Window, brush78);
    QBrush brush79(QColor(0, 0, 0, 255));
    brush79.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush79);
    QBrush brush80(QColor(103, 141, 178, 255));
    brush80.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Inactive, QPalette::Highlight, brush80);
    QBrush brush81(QColor(255, 255, 255, 255));
    brush81.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush81);
    QBrush brush82(QColor(0, 0, 238, 255));
    brush82.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Inactive, QPalette::Link, brush82);
    QBrush brush83(QColor(82, 24, 139, 255));
    brush83.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush83);
    QBrush brush84(QColor(232, 232, 232, 255));
    brush84.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush84);
    QBrush brush85(QColor(128, 128, 128, 255));
    brush85.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush85);
    QBrush brush86(QColor(221, 223, 228, 255));
    brush86.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Disabled, QPalette::Button, brush86);
    QBrush brush87(QColor(255, 255, 255, 255));
    brush87.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Disabled, QPalette::Light, brush87);
    QBrush brush88(QColor(255, 255, 255, 255));
    brush88.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush88);
    QBrush brush89(QColor(85, 85, 85, 255));
    brush89.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush89);
    QBrush brush90(QColor(199, 199, 199, 255));
    brush90.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush90);
    QBrush brush91(QColor(199, 199, 199, 255));
    brush91.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Disabled, QPalette::Text, brush91);
    QBrush brush92(QColor(255, 255, 255, 255));
    brush92.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush92);
    QBrush brush93(QColor(128, 128, 128, 255));
    brush93.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush93);
    QBrush brush94(QColor(239, 239, 239, 255));
    brush94.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Disabled, QPalette::Base, brush94);
    QBrush brush95(QColor(239, 239, 239, 255));
    brush95.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Disabled, QPalette::Window, brush95);
    QBrush brush96(QColor(0, 0, 0, 255));
    brush96.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush96);
    QBrush brush97(QColor(86, 117, 148, 255));
    brush97.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Disabled, QPalette::Highlight, brush97);
    QBrush brush98(QColor(255, 255, 255, 255));
    brush98.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush98);
    QBrush brush99(QColor(0, 0, 238, 255));
    brush99.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Disabled, QPalette::Link, brush99);
    QBrush brush100(QColor(82, 24, 139, 255));
    brush100.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush100);
    QBrush brush101(QColor(232, 232, 232, 255));
    brush101.setStyle(Qt::SolidPattern);
    palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush101);
    custom_color_label->setPalette(palette1);
    custom_color_label->setFocusPolicy(Qt::NoFocus);
    custom_color_label->setFrameShape(QFrame::WinPanel);
    custom_color_label->setFrameShadow(QFrame::Raised);
    custom_color_label->setLineWidth(0);
    custom_color_label->setMidLineWidth(0);
    custom_color_label->setTextFormat(Qt::AutoText);
    custom_color_label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
    custom_color_label->setMargin(0);
    transparency_slider = new QSlider(coloring_group);
    transparency_slider->setObjectName(QString::fromUtf8("transparency_slider"));
    transparency_slider->setGeometry(QRect(10, 176, 206, 21));
    transparency_slider->setMinimumSize(QSize(0, 21));
    transparency_slider->setMinimum(0);
    transparency_slider->setMaximum(255);
    transparency_slider->setSingleStep(1);
    transparency_slider->setValue(0);
    transparency_slider->setOrientation(Qt::Horizontal);
    transparency_slider->setTickInterval(10);
    model_group = new QGroupBox(DisplayPropertiesData);
    model_group->setObjectName(QString::fromUtf8("model_group"));
    model_group->setGeometry(QRect(0, 0, 282, 238));
    textLabel1_2 = new QLabel(model_group);
    textLabel1_2->setObjectName(QString::fromUtf8("textLabel1_2"));
    textLabel1_2->setGeometry(QRect(10, 17, 260, 16));
    textLabel1_2->setAlignment(Qt::AlignCenter);
    model_type_combobox = new QComboBox(model_group);
    model_type_combobox->setObjectName(QString::fromUtf8("model_type_combobox"));
    model_type_combobox->setGeometry(QRect(8, 33, 265, 24));
    model_type_combobox->setMinimumSize(QSize(200, 24));
    model_type_combobox->setMaximumSize(QSize(2000, 24));
    model_type_combobox->setFocusPolicy(Qt::StrongFocus);
    model_type_combobox->setMaxCount(2147483647);
    model_type_combobox->setInsertPolicy(QComboBox::InsertAtBottom);
    model_type_combobox->setDuplicatesEnabled(true);
    textLabel1_2_2 = new QLabel(model_group);
    textLabel1_2_2->setObjectName(QString::fromUtf8("textLabel1_2_2"));
    textLabel1_2_2->setGeometry(QRect(10, 153, 260, 21));
    textLabel1_2_2->setAlignment(Qt::AlignCenter);
    model_updates_enabled = new QCheckBox(model_group);
    model_updates_enabled->setObjectName(QString::fromUtf8("model_updates_enabled"));
    model_updates_enabled->setGeometry(QRect(13, 202, 259, 27));
    mode_combobox = new QComboBox(model_group);
    mode_combobox->setObjectName(QString::fromUtf8("mode_combobox"));
    mode_combobox->setGeometry(QRect(9, 174, 263, 24));
    mode_combobox->setMinimumSize(QSize(200, 24));
    mode_combobox->setMaximumSize(QSize(1600, 24));
    mode_combobox->setFocusPolicy(Qt::StrongFocus);
    mode_combobox->setMaxCount(2147483647);
    mode_combobox->setInsertPolicy(QComboBox::InsertAtBottom);
    mode_combobox->setDuplicatesEnabled(true);
    resolution_group = new QGroupBox(model_group);
    resolution_group->setObjectName(QString::fromUtf8("resolution_group"));
    resolution_group->setGeometry(QRect(8, 67, 265, 80));
    resolution_group->setAlignment(Qt::AlignHCenter);
    presets_precision_label = new QLabel(resolution_group);
    presets_precision_label->setObjectName(QString::fromUtf8("presets_precision_label"));
    presets_precision_label->setGeometry(QRect(206, 19, 48, 20));
    presets_precision_label->setAlignment(Qt::AlignCenter);
    custom_precision_label = new QLabel(resolution_group);
    custom_precision_label->setObjectName(QString::fromUtf8("custom_precision_label"));
    custom_precision_label->setGeometry(QRect(206, 50, 48, 20));
    custom_precision_label->setAlignment(Qt::AlignCenter);
    presets_precision_button = new QRadioButton(resolution_group);
    presets_precision_button->setObjectName(QString::fromUtf8("presets_precision_button"));
    presets_precision_button->setGeometry(QRect(8, 19, 87, 21));
    presets_precision_button->setChecked(true);
    custom_precision_button = new QRadioButton(resolution_group);
    custom_precision_button->setObjectName(QString::fromUtf8("custom_precision_button"));
    custom_precision_button->setGeometry(QRect(8, 49, 83, 21));
    precision_combobox = new QComboBox(resolution_group);
    precision_combobox->setObjectName(QString::fromUtf8("precision_combobox"));
    precision_combobox->setGeometry(QRect(99, 18, 100, 24));
    precision_combobox->setMinimumSize(QSize(100, 0));
    precision_combobox->setMaximumSize(QSize(100, 32767));
    precision_combobox->setFocusPolicy(Qt::StrongFocus);
    precision_combobox->setMaxCount(2147483647);
    precision_combobox->setInsertPolicy(QComboBox::InsertAtBottom);
    precision_combobox->setDuplicatesEnabled(true);
    precision_slider = new QSlider(resolution_group);
    precision_slider->setObjectName(QString::fromUtf8("precision_slider"));
    precision_slider->setGeometry(QRect(101, 51, 94, 21));
    precision_slider->setMinimumSize(QSize(90, 0));
    precision_slider->setMaximumSize(QSize(100, 32767));
    precision_slider->setMinimum(5);
    precision_slider->setMaximum(900);
    precision_slider->setSingleStep(1);
    precision_slider->setValue(30);
    precision_slider->setOrientation(Qt::Horizontal);
    precision_slider->setTickInterval(20);
    model_options = new QPushButton(DisplayPropertiesData);
    model_options->setObjectName(QString::fromUtf8("model_options"));
    model_options->setGeometry(QRect(1, 240, 280, 30));
    QSizePolicy sizePolicy3(static_cast<QSizePolicy::Policy>(3), static_cast<QSizePolicy::Policy>(0));
    sizePolicy3.setHorizontalStretch(0);
    sizePolicy3.setVerticalStretch(0);
    sizePolicy3.setHeightForWidth(model_options->sizePolicy().hasHeightForWidth());
    model_options->setSizePolicy(sizePolicy3);
    model_options->setMinimumSize(QSize(160, 30));
    model_options->setFocusPolicy(Qt::TabFocus);
    model_options->setAutoDefault(false);
    coloring_options = new QPushButton(DisplayPropertiesData);
    coloring_options->setObjectName(QString::fromUtf8("coloring_options"));
    coloring_options->setGeometry(QRect(287, 240, 280, 30));
    QSizePolicy sizePolicy4(static_cast<QSizePolicy::Policy>(0), static_cast<QSizePolicy::Policy>(0));
    sizePolicy4.setHorizontalStretch(0);
    sizePolicy4.setVerticalStretch(0);
    sizePolicy4.setHeightForWidth(coloring_options->sizePolicy().hasHeightForWidth());
    coloring_options->setSizePolicy(sizePolicy4);
    coloring_options->setMinimumSize(QSize(280, 30));
    coloring_options->setFocusPolicy(Qt::TabFocus);
    coloring_options->setAutoDefault(false);
    QWidget::setTabOrder(model_type_combobox, presets_precision_button);
    QWidget::setTabOrder(presets_precision_button, precision_combobox);
    QWidget::setTabOrder(precision_combobox, custom_precision_button);
    QWidget::setTabOrder(custom_precision_button, precision_slider);
    QWidget::setTabOrder(precision_slider, mode_combobox);
    QWidget::setTabOrder(mode_combobox, model_updates_enabled);
    QWidget::setTabOrder(model_updates_enabled, model_options);
    QWidget::setTabOrder(model_options, coloring_method_combobox);
    QWidget::setTabOrder(coloring_method_combobox, edit_selection);
    QWidget::setTabOrder(edit_selection, custom_button);
    QWidget::setTabOrder(custom_button, transparency_slider);
    QWidget::setTabOrder(transparency_slider, coloring_updates_enabled);
    QWidget::setTabOrder(coloring_updates_enabled, coloring_options);
    QWidget::setTabOrder(coloring_options, create_button);
    QWidget::setTabOrder(create_button, modify_button);
    QWidget::setTabOrder(modify_button, close_button);

    retranslateUi(DisplayPropertiesData);

    QSize size(570, 310);
    size = size.expandedTo(DisplayPropertiesData->minimumSizeHint());
    DisplayPropertiesData->resize(size);


    mode_combobox->setCurrentIndex(2);
    precision_combobox->setCurrentIndex(2);


    QMetaObject::connectSlotsByName(DisplayPropertiesData);
    } // setupUi

    void retranslateUi(QDialog *DisplayPropertiesData)
    {
    DisplayPropertiesData->setWindowTitle(QApplication::translate("DisplayPropertiesData", "Display Settings", 0, QApplication::UnicodeUTF8));
    modify_button->setToolTip(QApplication::translate("DisplayPropertiesData", "Modify the highlighted representation", 0, QApplication::UnicodeUTF8));
    modify_button->setText(QApplication::translate("DisplayPropertiesData", "&Modify", 0, QApplication::UnicodeUTF8));
    modify_button->setShortcut(QApplication::translate("DisplayPropertiesData", "Alt+M", 0, QApplication::UnicodeUTF8));
    create_button->setToolTip(QApplication::translate("DisplayPropertiesData", "Create a new representation for the highlighted molecular Entities", 0, QApplication::UnicodeUTF8));
    create_button->setText(QApplication::translate("DisplayPropertiesData", "&Create", 0, QApplication::UnicodeUTF8));
    create_button->setShortcut(QApplication::translate("DisplayPropertiesData", "Alt+C", 0, QApplication::UnicodeUTF8));
    close_button->setToolTip(QApplication::translate("DisplayPropertiesData", "Close window and discard changes", 0, QApplication::UnicodeUTF8));
    close_button->setText(QApplication::translate("DisplayPropertiesData", "&Close", 0, QApplication::UnicodeUTF8));
    close_button->setShortcut(QApplication::translate("DisplayPropertiesData", "Alt+C", 0, QApplication::UnicodeUTF8));
    coloring_group->setTitle(QApplication::translate("DisplayPropertiesData", "Color", 0, QApplication::UnicodeUTF8));
    textLabel1->setText(QApplication::translate("DisplayPropertiesData", "Coloring Method", 0, QApplication::UnicodeUTF8));
    textLabel1_2_2_2->setText(QApplication::translate("DisplayPropertiesData", "Transparency", 0, QApplication::UnicodeUTF8));
    transparency_label->setText(QApplication::translate("DisplayPropertiesData", "0%", 0, QApplication::UnicodeUTF8));
    coloring_updates_enabled->setText(QApplication::translate("DisplayPropertiesData", "automatic update", 0, QApplication::UnicodeUTF8));
    selection_group->setTitle(QApplication::translate("DisplayPropertiesData", "Selection", 0, QApplication::UnicodeUTF8));
    edit_selection->setText(QApplication::translate("DisplayPropertiesData", "Edit", 0, QApplication::UnicodeUTF8));
    custom_group->setTitle(QApplication::translate("DisplayPropertiesData", "Default / Custom", 0, QApplication::UnicodeUTF8));
    custom_button->setText(QApplication::translate("DisplayPropertiesData", "Edit", 0, QApplication::UnicodeUTF8));
    transparency_slider->setToolTip(QApplication::translate("DisplayPropertiesData", "Select level of transparency", 0, QApplication::UnicodeUTF8));
    model_group->setTitle(QApplication::translate("DisplayPropertiesData", "Model", 0, QApplication::UnicodeUTF8));
    textLabel1_2->setText(QApplication::translate("DisplayPropertiesData", "Type", 0, QApplication::UnicodeUTF8));
    model_type_combobox->setToolTip(QApplication::translate("DisplayPropertiesData", "Select model type", 0, QApplication::UnicodeUTF8));
    textLabel1_2_2->setText(QApplication::translate("DisplayPropertiesData", "Drawing Mode", 0, QApplication::UnicodeUTF8));
    model_updates_enabled->setText(QApplication::translate("DisplayPropertiesData", "automatic update", 0, QApplication::UnicodeUTF8));
    mode_combobox->clear();
    mode_combobox->addItem(QApplication::translate("DisplayPropertiesData", "dots", 0, QApplication::UnicodeUTF8));
    mode_combobox->addItem(QApplication::translate("DisplayPropertiesData", "wireframe", 0, QApplication::UnicodeUTF8));
    mode_combobox->addItem(QApplication::translate("DisplayPropertiesData", "solid", 0, QApplication::UnicodeUTF8));
    mode_combobox->addItem(QApplication::translate("DisplayPropertiesData", "toon", 0, QApplication::UnicodeUTF8));
    resolution_group->setTitle(QApplication::translate("DisplayPropertiesData", "Resolution", 0, QApplication::UnicodeUTF8));
    presets_precision_label->setText(QApplication::translate("DisplayPropertiesData", "6.5", 0, QApplication::UnicodeUTF8));
    custom_precision_label->setText(QApplication::translate("DisplayPropertiesData", "6.5", 0, QApplication::UnicodeUTF8));
    presets_precision_button->setText(QApplication::translate("DisplayPropertiesData", "presets", 0, QApplication::UnicodeUTF8));
    custom_precision_button->setText(QApplication::translate("DisplayPropertiesData", "custom", 0, QApplication::UnicodeUTF8));
    precision_combobox->clear();
    precision_combobox->addItem(QApplication::translate("DisplayPropertiesData", "low", 0, QApplication::UnicodeUTF8));
    precision_combobox->addItem(QApplication::translate("DisplayPropertiesData", "medium", 0, QApplication::UnicodeUTF8));
    precision_combobox->addItem(QApplication::translate("DisplayPropertiesData", "high", 0, QApplication::UnicodeUTF8));
    precision_combobox->addItem(QApplication::translate("DisplayPropertiesData", "ultra", 0, QApplication::UnicodeUTF8));
    precision_combobox->setToolTip(QApplication::translate("DisplayPropertiesData", "Select predefined resolution settings", 0, QApplication::UnicodeUTF8));
    precision_slider->setToolTip(QApplication::translate("DisplayPropertiesData", "Select your own resolution level", 0, QApplication::UnicodeUTF8));
    model_options->setToolTip(QApplication::translate("DisplayPropertiesData", "Advanced options for selected model", 0, QApplication::UnicodeUTF8));
    model_options->setText(QApplication::translate("DisplayPropertiesData", "Model Options", 0, QApplication::UnicodeUTF8));
    model_options->setShortcut(QString());
    coloring_options->setToolTip(QApplication::translate("DisplayPropertiesData", "Advanced options for selected coloring method", 0, QApplication::UnicodeUTF8));
    coloring_options->setText(QApplication::translate("DisplayPropertiesData", "Coloring Options", 0, QApplication::UnicodeUTF8));
    coloring_options->setShortcut(QString());
    Q_UNUSED(DisplayPropertiesData);
    } // retranslateUi

};

namespace Ui {
    class DisplayPropertiesData: public Ui_DisplayPropertiesData {};
} // namespace Ui

#endif // DISPLAYPROPERTIESDATA_H
