FIND_PATH(BIOH5_LIBRARY libBioh5.a  ${CMAKE_PREFIX_PATH} )
FIND_PATH(BIOH5_INCLUDE bioh5.h ${CMAKE_PREFIX_PATH} )

IF(BIOH5_INCLUDE AND BIOH5_LIBRARY)
  SET(BIOH5_FOUND 1 CACHE BOOL "Found BIOH5 library")
  SET(BIOH5_INCLUDE_DIR ${BIOH5_LIBRARY})
  SET(BIOH5_LIBRARY_DIRS ${BIOH5_LIBRARY})
ELSE(BIOH5_INCLUDE AND BIOH5_LIBRARY)
  SET(BIOH5_FOUND 0 CACHE BOOL "Not found BIOH5 library")
ENDIF(BIOH5_INCLUDE AND BIOH5_LIBRARY)

MARK_AS_ADVANCED(
  BIOH5_INCLUDE_DIR 
  BIOH5_LIBRARY 
  BIOH5_LIBRARY_DIRS 
  BIOH5_FOUND
)
